error in vec class when comparing lengths
mostly complete, need to investigate why test cases for same lengths
vec +vec, vec-vec, mul and right mul for floats and ints not
being liked on codepost. My initial thoughts are possibly on how
self and other comparisons are being done.

Error I am getting is:

if student_ans.elements != ans.elements:\nAttributeError:
\list' object has no attribute 'elements'