Add logic for mod_inv WIP
It returns some values of the inverse correctly
but crashes with message:

UnboundLocalError: cannot access local variable
'temp_s' where it is not associated with a value

Need to investigate further.